//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDoggo.Models
{
    using System;
    using System.Collections.Generic;
    using ProyectoFinalDoggo.clases;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using ProyectoFinalDoggo.Models;
    using System.Linq;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.compras = new HashSet<compras>();
            this.carrito = new HashSet<carrito>();
        }
        [Required(ErrorMessage = "El campo de Usuario es requerido.")]
        public string usuario { get; set; }
        [Required(ErrorMessage = "Contraseña es requerido.")]
        public string pass { get; set; }
        [Required(ErrorMessage = "El campo de Correo es requerido.")]
        public string correo { get; set; }
        [Required(ErrorMessage = "El campo de Dirección es requerido.")]
        public string direccion { get; set; }
        [Required(ErrorMessage = "El campo de Teléfono es requerido.")]
        public string telefono { get; set; }
        [Required(ErrorMessage = "El campo de Rol es requerido.")]
        public string rol { get; set; }
        [Required(ErrorMessage = "El Nombre es requerido.")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El Apellido es requerido.")]
        public string apellido { get; set; }
        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compras> compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrito> carrito { get; set; }
    }
}
